Approval service
seneca-vas/seneca-course-reviews-admin pull request #5
Opened 2021-10-04 19:13 UTC by michellengnx

2021-10-04 22:03 UTC, Andrewnt219 commented
https://github.com/seneca-vas/seneca-course-reviews-admin/pull/5/commits/d21bad4df5ea70a46c85f011daeba32f33f8eedc use `git rebase` next time

2021-10-04 22:04 UTC, Andrewnt219 requested changes

2021-10-04 22:04 UTC, Andrewnt219 commented on src/modules/course-reviews/service/course-reviews-service.ts
> +import { firestore } from "@lib/firebase";
This file does not belong to the admin repo. Please remove it.

2021-10-04 22:04 UTC, Andrewnt219 commented on src/modules/course-reviews/service/index.ts
> +export * from "./course-reviews-service"
This line does not belong to admin repo.

2021-10-04 23:55 UTC, michellengnx commented on src/modules/course-reviews/service/index.ts
> +export * from "./course-reviews-service"
Removed the line!

2021-10-04 23:56 UTC, michellengnx commented on src/modules/course-reviews/service/course-reviews-service.ts
> +import { firestore } from "@lib/firebase";
Done! Should I keep the model folder if the approval service simply change the isApproved value from false to true, which doesn't really need the CourseReview schema to do so for the time being?

2021-10-05 00:58 UTC, Andrewnt219 commented on src/modules/course-reviews/service/course-reviews-service.ts
> +import { firestore } from "@lib/firebase";
No, just set up an empty service.

2021-10-05 01:15 UTC, closed without merging

2021-10-05 03:40 UTC, Andrewnt219 commented
@michellengnx don't need to create a new PR next time, just push new commits and the PR is updated.